# Generated by Django 2.2.17 on 2020-12-01 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registar',
            fields=[
                ('registar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subscription_date', models.DateField(default=datetime.datetime(2015, 1, 1, 0, 0))),
                ('name', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('dept', models.FloatField(default=0.0)),
            ],
        ),
    ]
